apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: mondoo-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-mondoo-com
  failurePolicy: Ignore
  name: policy.k8s.mondoo.com
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-public
      - kube-node-lease
      - gke-managed-system
      - gke-managed-cim
      - gke-managed-filestorecsi
      - gke-managed-parallelstorecsi
      - gke-managed-volumepopulator
      - gke-gmp-system
      - gmp-public
  rules:
  - apiGroups:
    - ""
    - apps
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - deployments
    - daemonsets
    - statefulsets
    - jobs
    - cronjobs
  sideEffects: None
  timeoutSeconds: 20
