# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Uncomment the following 4 lines to enable RBAC-authenticated secure metrics.
# Required when using --secure-metrics flag.
#- auth_proxy_service.yaml
#- auth_proxy_role.yaml
#- auth_proxy_role_binding.yaml
#- auth_proxy_client_clusterrole.yaml
# Comment the following lines to self manage roles for the workload
- k8s_resources_scanning_service_account.yaml
- k8s_resources_scanning_clusterrole.yaml
- k8s_resources_scanning_clusterrolebinding.yaml
- webhook_service_account.yaml
