# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runtime-cache-scanning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runtime-cache-scanning
subjects:
- kind: ServiceAccount
  name: mondoo-operator-runtime-cache-scanning
  namespace: system
