{{- if .Values.operator.createConfig }}
apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooOperatorConfig
metadata:
  name: mondoo-operator-config
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
spec:
  {{- $spec := dict }}
  {{- if .Values.operator.httpProxy }}
  {{- $_ := set $spec "httpProxy" .Values.operator.httpProxy }}
  {{- end }}
  {{- if .Values.operator.httpsProxy }}
  {{- $_ := set $spec "httpsProxy" .Values.operator.httpsProxy }}
  {{- end }}
  {{- if .Values.operator.noProxy }}
  {{- $_ := set $spec "noProxy" .Values.operator.noProxy }}
  {{- end }}
  {{- if .Values.operator.containerProxy }}
  {{- $_ := set $spec "containerProxy" .Values.operator.containerProxy }}
  {{- end }}
  {{- if .Values.operator.imagePullSecrets }}
  {{- $_ := set $spec "imagePullSecrets" .Values.operator.imagePullSecrets }}
  {{- end }}
  {{- if .Values.operator.imageRegistry }}
  {{- $_ := set $spec "imageRegistry" .Values.operator.imageRegistry }}
  {{- end }}
  {{- if .Values.operator.registryMirrors }}
  {{- $_ := set $spec "registryMirrors" .Values.operator.registryMirrors }}
  {{- end }}
  {{- if .Values.operator.skipContainerResolution }}
  {{- $_ := set $spec "skipContainerResolution" .Values.operator.skipContainerResolution }}
  {{- end }}
  {{- if .Values.operator.skipProxyForCnspec }}
  {{- $_ := set $spec "skipProxyForCnspec" .Values.operator.skipProxyForCnspec }}
  {{- end }}
  {{- $spec | toYaml | nindent 2 }}
{{- end }}
