// Code generated by protoc-gen-actions DO NOT EDIT.
// source: captain.proto

package policy

const (
	ACTION_MONDOO_POLICY_ASSETSTORE_LISTASSETS   = "mondoo.policy.AssetStore.ListAssets"
	ACTION_MONDOO_POLICY_ASSETSTORE_DELETEASSETS = "mondoo.policy.AssetStore.DeleteAssets"
)
