// Code generated by protoc-gen-rangerrpc version DO NOT EDIT.
// source: policy.proto

package policy

import (
	"context"
	"errors"
	"net/http"
	"net/url"
	"strings"

	ranger "go.mondoo.com/ranger-rpc"
	"go.mondoo.com/ranger-rpc/metadata"
	jsonpb "google.golang.org/protobuf/encoding/protojson"
	pb "google.golang.org/protobuf/proto"
)

// service interface definition

type AssetStore interface {
	ListAssets(context.Context, *AssetSearchFilter) (*AssetsPage, error)
	DeleteAssets(context.Context, *DeleteAssetsRequest) (*DeleteAssetsConfirmation, error)
	ListCicdProjects(context.Context, *ListCicdProjectsRequest) (*CicdProjectsPage, error)
	DeleteCicdProjects(context.Context, *DeleteCicdProjectsRequest) (*DeleteCicdProjectsConfirmation, error)
}

// client implementation

type AssetStoreClient struct {
	ranger.Client
	httpclient ranger.HTTPClient
	prefix     string
}

func NewAssetStoreClient(addr string, client ranger.HTTPClient, plugins ...ranger.ClientPlugin) (*AssetStoreClient, error) {
	base, err := url.Parse(ranger.SanitizeUrl(addr))
	if err != nil {
		return nil, err
	}

	u, err := url.Parse("./AssetStore")
	if err != nil {
		return nil, err
	}

	serviceClient := &AssetStoreClient{
		httpclient: client,
		prefix:     base.ResolveReference(u).String(),
	}
	serviceClient.AddPlugins(plugins...)
	return serviceClient, nil
}
func (c *AssetStoreClient) ListAssets(ctx context.Context, in *AssetSearchFilter) (*AssetsPage, error) {
	out := new(AssetsPage)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/ListAssets"}, ""), in, out)
	return out, err
}
func (c *AssetStoreClient) DeleteAssets(ctx context.Context, in *DeleteAssetsRequest) (*DeleteAssetsConfirmation, error) {
	out := new(DeleteAssetsConfirmation)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/DeleteAssets"}, ""), in, out)
	return out, err
}
func (c *AssetStoreClient) ListCicdProjects(ctx context.Context, in *ListCicdProjectsRequest) (*CicdProjectsPage, error) {
	out := new(CicdProjectsPage)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/ListCicdProjects"}, ""), in, out)
	return out, err
}
func (c *AssetStoreClient) DeleteCicdProjects(ctx context.Context, in *DeleteCicdProjectsRequest) (*DeleteCicdProjectsConfirmation, error) {
	out := new(DeleteCicdProjectsConfirmation)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/DeleteCicdProjects"}, ""), in, out)
	return out, err
}

// server implementation

type AssetStoreServerOption func(s *AssetStoreServer)

func WithUnknownFieldsForAssetStoreServer() AssetStoreServerOption {
	return func(s *AssetStoreServer) {
		s.allowUnknownFields = true
	}
}

func NewAssetStoreServer(handler AssetStore, opts ...AssetStoreServerOption) http.Handler {
	srv := &AssetStoreServer{
		handler: handler,
	}

	for i := range opts {
		opts[i](srv)
	}

	service := ranger.Service{
		Name: "AssetStore",
		Methods: map[string]ranger.Method{
			"ListAssets":         srv.ListAssets,
			"DeleteAssets":       srv.DeleteAssets,
			"ListCicdProjects":   srv.ListCicdProjects,
			"DeleteCicdProjects": srv.DeleteCicdProjects,
		},
	}
	return ranger.NewRPCServer(&service)
}

type AssetStoreServer struct {
	handler            AssetStore
	allowUnknownFields bool
}

func (p *AssetStoreServer) ListAssets(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req AssetSearchFilter
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.ListAssets(ctx, &req)
}
func (p *AssetStoreServer) DeleteAssets(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req DeleteAssetsRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.DeleteAssets(ctx, &req)
}
func (p *AssetStoreServer) ListCicdProjects(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req ListCicdProjectsRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.ListCicdProjects(ctx, &req)
}
func (p *AssetStoreServer) DeleteCicdProjects(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req DeleteCicdProjectsRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.DeleteCicdProjects(ctx, &req)
}
