// Code generated by protoc-gen-actions DO NOT EDIT.
// source: captain.proto

package integrations

const (
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_LIST                   = "mondoo.integrations.IntegrationsManager.List"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_GET                    = "mondoo.integrations.IntegrationsManager.Get"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_GETNAME                = "mondoo.integrations.IntegrationsManager.GetName"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_GETTOKENFORINTEGRATION = "mondoo.integrations.IntegrationsManager.GetTokenForIntegration"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_CREATE                 = "mondoo.integrations.IntegrationsManager.Create"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_UPDATE                 = "mondoo.integrations.IntegrationsManager.Update"
	ACTION_MONDOO_INTEGRATIONS_INTEGRATIONSMANAGER_DELETE                 = "mondoo.integrations.IntegrationsManager.Delete"
)
