// Code generated by protoc-gen-actions DO NOT EDIT.
// source: captain.proto

package captain

const (
	ACTION_MONDOO_CAPTAIN_CAPTAIN_LISTSPACES  = "mondoo.captain.Captain.ListSpaces"
	ACTION_MONDOO_CAPTAIN_CAPTAIN_DELETESPACE = "mondoo.captain.Captain.DeleteSpace"
	ACTION_MONDOO_CAPTAIN_CAPTAIN_CREATESPACE = "mondoo.captain.Captain.CreateSpace"
	ACTION_MONDOO_CAPTAIN_CAPTAIN_GETSPACE    = "mondoo.captain.Captain.GetSpace"
)
