---
name: Link Checking

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  md-links:
    name: Run markdown link check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-verbose-mode: "yes"
          config-file: ".github/actions/link-check/config.json"
